python run_tests_safety.py \
        --sut "gpt-4o-mini" \
        --judge "gpt-4o-mini" \
        --generator "gpt-4o-mini" \
        --fitness "gpt-4o-mini" \
        --population_size 5 \
        --n_generations 5 \
        --algorithm "nsga2" \
        --max_time "00:05:00" \
        --features_config "configs/safety_features.json"\
        --no_wandb \
        --no_rag \
        --results_folder "results/tests/safety/cloud/" \
        --seed 1